version: '3.8'

services:

  mcp-link:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mcp-link-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://10.10.16.12:47017
      - MONGODB_DATABASE=omnimcp
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    volumes:
      - ./config:/app/config